apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  host: "stip.uat.apps.test.kibon.ch"
  host-sb: "stip-sb.uat.apps.test.kibon.ch"
  identityHost: "auth.stip.uat.apps.test.kibon.ch"
